// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Convert(arg1:number,arg2:string,arg3:string):Promise<main.ConvertResult>;

export function GetCurrencyList():Promise<Array<main.Currency>>;

export function GetRates(arg1:string,arg2:string):Promise<Array<main.RateRow>>;

export function GetSystemLanguage():Promise<string>;

export function GetSystemTheme():Promise<string>;

export function LoadSettingsData():Promise<main.Settings>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;
