// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1, arg2, arg3) {
  return window['go']['main']['App']['Convert'](arg1, arg2, arg3);
}

export function GetCurrencyList() {
  return window['go']['main']['App']['GetCurrencyList']();
}

export function GetRates(arg1, arg2) {
  return window['go']['main']['App']['GetRates'](arg1, arg2);
}

export function GetSystemLanguage() {
  return window['go']['main']['App']['GetSystemLanguage']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function LoadSettingsData() {
  return window['go']['main']['App']['LoadSettingsData']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}
